### ISSUE TITLE
tmux console not working

### ISSUE THREAD

**Issue by frootmig** [churchers/vm-bhyve#119]
Hi,

I installed this version of vm-bhyve: Bhyve virtual machine management v1.1-p4 (build 101065)
on my FreeBSD 11-RC3

And I followed the tmux instructions from the wiki. The guide does not seems to work:

tmux ls
no server running on /tmp/tmux-0/default

I have never seen a VM console in an open tmux, too.

Any advice what might cause this problem?

**Comment by frootmig** [comment]
I think I was able to isolate the problem: after looking at the code I found that I need to use the current trunk version to get tmux working with my setup.

**Comment by churchers** [comment]
Glad you got it working. Did you have dots in the machine names or was it something else?

**Comment by frootmig** [comment]
Yes, I am using FQDN as VMs names which caused the problems. I'm new to tmux, didn't know dot is not allowed. Was confused that the fix was in no patch release yet. Your scripts are now working fine.

**Comment by churchers** [comment]
Yeah I'm also new to tmux and wasn't sure about session name limitations originally. I expected dots to be ok but it uses them to separate `session-name.pane`.

I updated the code a while ago but haven't been around to get it submitted to ports. I've just submitted a PR for the ports tree, hopefully it'll be merged before the October quarterly snapshot is taken.

**Comment by frootmig** [comment]
By the way: vm -f install does not open a tmux session, is that intended?

And I was seeking a way to autostart VMs. Can't find a documentation hint how to achieve this.

**Comment by churchers** [comment]
`vm -f` is foreground mode. Everything is run directly on stdio. This option has been around since before I added tmux support and was useful for installs, as you often don't get to see the boot loader screen if a guest is started in the background - And saved starting the guest then directly having to run `vm console guest` to get into the installer. Also if people want to use some other terminal manager then can create their own sessions, then just run `vm -f` to have it run directly in that session.

If you have vm-bhyve 1.2 and it's configured to use tmux, you can use interactive mode - `vm -i`. This is useful as it works like foreground mode, but is still using tmux, so you can detach and leave the guest running in the background. With foreground mode you can't get out of the guest without shutting it down.

To autostart VMs on boot just add them to the `vm_list=""` setting in `/etc/rc.conf`, separated by a space. You should then see the Autostart property show as Yes in `vm list` output. They are started in the order they are specified in the variable and you can also use `vm_delay="X"` to set the delay between starting them. I'm sure it' mentioned somewhere in the README and man page.
