### ISSUE TITLE
16 character guest name limit?

### ISSUE THREAD

**Issue by roy-integral** [churchers/vm-bhyve#122]
Was hoping to be able to name guests after their fqdn, but get an error after 16 characters.

There a way around this or do I need to think of a more complex naming scheme?

**Comment by churchers** [comment]
Yes it's been limited to 16 characters since the start, although that's probably a bit conservative.
It's controlled by the `check_name` function in `lib/vm-core`. That function limits guest & switch names to 14 characters plus one at the beginning/end.

I will find out what the maximum allowed by bhyve is and increase it.

**Comment by churchers** [comment]
I've increased the maximum length to 32 characters in the current GitHub version.
This seems to be the current limit for bhyve - 

    sys/amd64/include/vmm.h:#define VM_MAX_NAMELEN  32

To go any further than that would take much bigger changes to the code. I will likely stay with the guest name in vm-bhyve being directly mapped to the bhyve guest name, and thus bound by the same restrictions.
