### ISSUE TITLE
Feature request: vm snapshot and rollback

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#15]
I know for other fs than zfs, snapshot is not easy for vm-bhyve to do.
but when using zfs as backend, it is possible.
I know when I use 
```
root@qnas:~/vm-bhyve # vm clone win2012 win2013
```
vm-bhyve will snapshot the source vm, and clone to dest vm.
```
root@qnas:~/vm-bhyve # zfs list
NAME                    USED  AVAIL  REFER  MOUNTPOINT
tank/vm                10.7G  2.62T  3.93G  /vm
tank/vm/win2012        6.76G  2.62T   104K  /vm/win2012
tank/vm/win2012/disk0  6.76G  2.62T  6.76G  -
tank/vm/win2013          76K  2.62T   100K  /vm/win2013
tank/vm/win2013/disk0     8K  2.62T  6.76G  -
root@qnas:~/vm-bhyve # zfs list -t snapshot
NAME                             USED  AVAIL  REFER  MOUNTPOINT
tank/vm/win2012@342a3d90            0      -   104K  -
tank/vm/win2012/disk0@342a3d90      0      -  6.76G  -
```
Base on this, I think we can have ```snapshot``` and ```rollback``` command.

**Comment by churchers** [comment]
Yeah I was originally reluctant to add too many commands that were zfs only. One of the reasons I decided to write `vm-bhyve` was that I wanted something that worked with zfs, but ran just as well for people using ufs/nfs.

My original reason for implementing `clone` and not the others was because it requires the guest configuration file to be renamed. `snapshot` and `rollback` can be achieved purely by running zfs commands.

Having said that it appears that `rollback` doesn't support descendent datasets, so you have to rollback the guest and any zvols separately. It's quite annoying that `snapshot` can be recursive, but both `clone` and `rollback` only work on one dataset...

Anyway, I probably will implement these, more for convenience than anything else. `snapshot` is basically just one command and `rollback` can borrow a lot of the code from the `clone` function.

**Comment by churchers** [comment]
I've added these commands and think I made a pretty good job of it :)

I originally starting writing it to work as `vm snapshot guest snapshot`. However, almost immediately in testing I automatically typed `vm snapshot guest@snapshot` like I would for ZFS, so decided to use that syntax instead (which was slightly more difficult). If no snapshot name is given (i.e `vm snapshot guest`), it just uses the date & time. Also, the guest must be stopped, although you can override this with `-f` (force).

For `rollback` you must specify the guest & snapshot - `vm rollback guest@snapshot`. In this case I actually display errors from ZFS directly. If the snapshot isn't the most recent, ZFS will error that you need to destroy the more recent snapshots, and give a list of them. It will also mention using `-r` to force the rollback. In this case I thought it made most sense to display these errors directly (so the user can see which snapshots are "in the way"), and to then support passing the `-r` option so `vm rollback -r guest@snapshot` will force the rollback and delete all the newer snapshots that zfs listed.

This is also covered in the man page.

**Comment by WanpengQian** [comment]
Just have a quick test, works as expected. 
nice job! ;-)
