### ISSUE TITLE
Unable to remove virtual switch

### ISSUE THREAD

**Issue by ttocsr** [churchers/vm-bhyve#167]
I'm at a loss how to remove this virtual switch. 

     # vm switch info
    ------------------------
    Virtual Switch: public
    ------------------------
    type: auto
    ident: -
    vlan: -
    nat: -
    physical-ports: igb2

    #vm switch destroy public
    /usr/local/sbin/vm: ERROR: failed to get switch id while removing members

    #vm switch remove public igb2
    /usr/local/sbin/vm: ERROR: unable to locate virtual switch`

**Comment by churchers** [comment]
vm-bhyve attempts to remove all members from the bridge interface and remove the bridge when a switch is deleted. Looking at the info output, it can't find the bridge interface related to this switch. (It basically looks for `description: vm-public` in `ifconfig` output. Normally it would show something like `ident: bridge1`.

I'm guessing the bridge isn't there at all although I don't know if it's been removed manually or is due to a bug in vm-bhyve. A reboot should cause vm-bhvye to recreate the bridge for this switch, at which point the ident (interface name) should show up and removing it should work.

Alternatively you can edit `${vm_dir}/.config/system.conf` (or `${vm_dir}/.config/switch` depending on the version) and remove the references to this switch.

**Comment by churchers** [comment]
Closing this for now. Switch code has changed extensively since.
Please open a new issue if this problem continues in v1.2

**Comment by rishabh27892** [comment]
I am facing a similar issue in v1.2!!
vm-bhyve: Bhyve virtual machine management v1.2 (build 102070)
# vm switch info public
------------------------
Virtual Switch: public
------------------------
  type: standard
  ident: -
  vlan: -
  physical-ports: re0

# vm switch destroy public
/usr/local/sbin/vm: ERROR: failed to remove virtual switch
# vm list
NAME          DATASTORE  LOADER  CPU  MEMORY  VNC  AUTOSTART  STATE
ubuntuTestvm  default    grub    1    4097M   -    No         Stopped
#
