### ISSUE TITLE
define root partition in vm config

### ISSUE THREAD

**Issue by abishai** [churchers/vm-bhyve#17]
Hello.

I have issues with CentOS installation with hostname set in installer. It that case, root partition is named as /dev/mapper/centos_$HOSTNAME-root, resulting unbootable system. As boot.cmd is regenerated every time, this can be a problem :)

Suggestions
1. Pass root partition name from vm config
2. Do not regenerate boot.cmd, allowing users to edit it once created.

**Comment by donnex** [comment]
I'm having the same issue with an Ubuntu install.

Are there any manual fixes? I haven't figured out yet how to tell Grub to load the correct kernel.

**Comment by churchers** [comment]
Unfortunately trying to automate the boot process seems to have its downsides. I'm sure I've actually given CentOS a hostname during my tests, but I suspect the boot commands might need adjusting depending on the install method/disk partitioning choices.

I'll have to do some testing but I think the best idea I have at the moment is to create a generic linux guest that by default makes no attempt to automate the loader commands. In that configuration you'd be able to connect to the guest console and enter grub commands manually.

I can then add something like a `grub_commands="filename"` configuration option. If specified, `vm-bhyve` can pass the contents of that file directly to `grub-bhyve`.

**Comment by abishai** [comment]
Enter grub commands manually? But we'll lose automatic start of VMs then.

**Comment by abishai** [comment]
Actually, if we speak about automatic start, I think vm init should sweep lock files left after host reboot.

**Comment by churchers** [comment]
There's no way I can automatically generate the correct grub commands for every possible configuration. This is why I mentioned a `grub_commands` configuration option. Once you know the correct grub commands, you can create a file containing these commands, add it to the configuration file, and `vm-bhyve` will pass those commands on each boot, which should allow autostart to be used.

Regarding clearing lock files, it does seem like a good idea, although in a multi-server environment it may end up unlocking guests that are actually running on another machine. I'll have to look at possible solutions for locked guests after a unclean shutdown.

**Comment by abishai** [comment]
Ah, I see. Yes, the ability to enter grub commands to setup boot environment and save them for future use would be great.

Unclean shutdown - yes, but I'm sure I made a simple reboot. Or I have to shutdown VMs manually first?

**Comment by churchers** [comment]
It should run the `/usr/local/etc/rc.d/vm stop` command on shutdown to stop the guests. However it depends on the command used. `shutdown -r now` should do a full clean shutdown. `reboot` is a bit more ugly and just kills everything. I don't know if it will still wait for bhyve to shutdown (or if it does how long it will wait), but if the `vm _run` processes get killed first, the lock files will get left around.

Personally I would recommend shutting down guests manually in a real environment and rebooting once everything is confirmed off. With `shutdown -r now` it should cleanly stop guests but unlike stuff like ESXi that will wait indefinitely and give up if guests are still running, we have less control over the shutdown process. There's also guests like Windows that seem to be a bit intermittent about accepting poweroff events (Mentioned in a separate issue).

**Comment by churchers** [comment]
For the time being I have added a `grub_commands="mycommands.txt"` option. Enter the correct grub commands for your guest into a file inside `$vm_dir/guest/`, then put the filename (just the name not the full path) into the configuration file.

The contents of the file will be something along the lines of the below. Make sure there is a newline at the end of the file otherwise the last command may be entered into grub but not executed.

    linux ........
    initrd ..........
    boot

This at least allows Linux guests to be started without manual intervention when the grub commands need to be different to the automatic ones, although you do need to work out the exact commands yourself**

I may look at rewriting the guest support in the near future to make it more configurable.

**You can set `guest=linux`, which is a generic linux guest that provides no automated commands to `grub-bhyve` (unless `boot_commands` is set). The vm will halt at the bootloader, at which point you can connect to the console and enter grub commands. Once you have the correct commands, create the `grub_commands` file, and it will then use these during next boot.

I'm not sure exactly why the grub command sometimes gets stuck on one line. This is something to do with the way `cu` and `nmdm` are working and I'm no expert of terminals. I have noticed however that runing `clear` in the grub console seems to help.

**Comment by churchers** [comment]
Closing this for now.
I think the ability to define custom grub commands is the best way I can come up with for supporting Linux guests when the automated commands aren't correct.
