### ISSUE TITLE
clean init errors

### ISSUE THREAD

**Issue by meabandit** [churchers/vm-bhyve#18]
On 10.2 RELEASE:

    # vm init
    cat: /usr/local/bhyve/vm/.config/switch: No such file or directory

**Comment by churchers** [comment]
Ah, I've changed the way configuration files are read, but obviously not tested it when the config file doesn't exist. It should be fine to ignore the error. You can silence this by either creating an empty file, or creating at least one virtual switch.

    touch /usr/local/bhyve/vm/.config/switch [OR]
    vm switch create switch-name

I'll need to update vm-bhyve to either create this file is it doesn't exist, or update the __config_load function so it doesn't produce an error if the file doesn't exist.

Thanks for the report.

**Comment by churchers** [comment]
This is fixed in latest GitHub master - `vm-bhyve 0.9.3`
It will now hide any error message when it attempts to read the config file. If the file doesn't exist, it will just load an empty configuration, which is what needs to happen anyway.

I'm planning to try and create a stable 1.0 release soon, at which point I'll get the package/port updated.

**Comment by meabandit** [comment]
Thanks, the other bhyve mgm tool is in worse shape so this one it great.  Also has better design.  

You might want to contact doc@ and see if you have get mentioned in the handbook.  Otherwise knowledge of this utility isn't readily available.
