### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by heshriti** [churchers/vm-bhyve#199]
when I initialize, using :  vm init
I get this:

/usr/local/sbin/vm: ERROR: unable to load vmm.ko!

I tried many things, including rebooting the machine. No luck.

Can you suggest what I can do to resolve?

thank you very much.

**Comment by heshriti** [comment]
hi, any thoughts on this? thanks in advance.

**Comment by handcode** [comment]
what's the output if you try to load the vmm module without vm?

`kldload vmm`

**Comment by heshriti** [comment]
$ sudo kldload vmm
kldload: can't load vmm: module already loaded or in kernel

**Comment by handcode** [comment]
If the module is already loaded, kldstat has to return an error, see: [util::load_module](https://github.com/churchers/vm-bhyve/blob/a85ef7c4e9f1ba69e76af39a6c0de89086839002/lib/vm-util#L42)

what's the output of:
`kldstat -v -m vmm && echo "kldstat returned success" || echo "kldstat returned error"`

**Comment by heshriti** [comment]
The kldstat does not recognize vmm:

$ kldstat -v -m vmm && echo "kldstat returned success" || echo "kldstat returned error"
kldstat: can't find module vmm: No such file or directory
kldstat returned error

**Comment by heshriti** [comment]
But plain kldstat seems to show that vmm is loaded, as follows

$ kldstat

Id Refs Address            Size     Name
 8    1   ... ....     vmm.ko

**Comment by heshriti** [comment]
sorry, so what's the solution for this?

**Comment by handcode** [comment]
then I guess the error occurs when initializing the module. try unload/load the module and search for error in dmesg.
```
kldunload vmm
kldload vmm
```
if you see a error like this in dmesg, your CPU is not supported
```
vmx_init: processor does not support VMX operation
module_register_init: MOD_LOAD (vmm, 0xffffffff8205f230, 0) error 6
```
see: https://www.freebsd.org/doc/handbook/virtualization-host-bhyve.html , https://wiki.freebsd.org/bhyve#Troubleshooting

**Comment by heshriti** [comment]
I went ahead with the installation, actually unloading the kernel and loading back. 
the switches seem to be there- swith list dhows ident etc..

But installation fails here:
$ sudo vm -f install ubuntu ubuntu-16.04.3-server-amd64.iso
Could not create VM vmubuntu
Error in initializing VM

Any thoughts?

**Comment by heshriti** [comment]
Jens,

as yo suggested, I unloaded and reloaded vmm, and that seems to at least
initialize the vm module. I was also able to get the switch to work
However, the vm setup just fails.

$ sudo vm -f install ubuntu ubuntu-16.04.3-server-amd64.iso
Could not create VM ubuntu
Error in initializing VM

**Comment by heshriti** [comment]
here are the logs:
Feb 14 18:02:42: initialising network device tap0
Feb 14 18:02:42: adding tap0 -> bridge0 (public)
Feb 14 18:02:42: booting
..
Feb 14 18:02:42: /usr/local/sbin/grub-bhyve -m /tmp/ubuntu/device.map -M 2G
 -r cd0 ubuntu
Feb 14 18:02:42: fatal; loader returned error 1
Feb 14 18:02:42: destroying network device tap0
Feb 14 18:02:42: stopped
~

**Comment by handcode** [comment]
I recommended that you unload/load the module and look for errors in dmesg or /var/log/messages.

Obviously the module is loaded but not initialized correctly.

That's why I still guess that your CPU is not supported or EPT is not activated in BIOS and therefore it doesn't make any sense to try to start a VM because this can't work without a correctly initialized vmm module

**Comment by 0mp** [comment]
Related: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227880

It looks like `kldstat -m vmm` does not work while `kldstat -n vmm` does.

**Comment by churchers** [comment]
This appears to be due to issues loading the vmm module, most likely due to missing hardware support.

Either way this doesn't seem to be an issue with vm-bhyve, and if the module can be loaded, which is obviously required, then both `kldstat -n` & `kldstat -m` should work. In fact as per the bug above, the current `-n` method needs to be used as `-m` may return true if some parts of `vmm.ko` are loaded (ppt and ivhd), but not the `vmm` module we actually need.
