### ISSUE TITLE
Feature request for FreeNAS iscsi integration

### ISSUE THREAD

**Issue by TomekadaScientiam** [churchers/vm-bhyve#204]
The other night my sisters and I where  sitting around playing with our FreeNAS mini(s) hoping to make a few VMS. This lead us to a web search where we found found a groovy project making use of your VM-bhyve. This project is a group of  FreeNAS/TrueNAS scripts to help / hook into vm-bhyve for iSCSI creation. 

https://github.com/daviddpd/ixnas-api

**Comment by nihr43** [comment]
I am not affiliated with the vm-bhyve project, but I do not believe iscsi integration is within the scope of vm-bhyve.

in my opinion, its best to make small tools that do single tasks well, to be used by higher-level management tools implemented on a per-case basis.  vm-bhyve is great because its manages bhyves well and thats all it does (excluding some host networking).  In the grand scheme of things, i prefer a good vm tool to manage vms, a good storage tool to manage storage, and ansible/puppet to rule them all.

**Comment by churchers** [comment]
I agree with the above. I don't think specific integration with FreeNAS is within the scope of vm-bhyve. It also appears to need http/json api support which isn't really viable from shell script.

I may look at more options for specifying disks, which may help with this sort of functionality though. Currently `vm-bhvye` has a very simple requirement of at least one local disk when creating a guest. If using iSCSI, you may want to specify an iSCSI target as the primary disk which currently isn't as easy as it could be. I've also had requests for support for live systems with no disk devices.
