### ISSUE TITLE
need an option when create zvol backend disk.

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#21]
when create a vm from template or add disk to an existing vm. if disk type is zvol/zvol-sparse, there is no way to set the volblocksize when creating. while this parameter is a little importance, affect the guest's disk performance. 

here is the compare result. 
using file backend.
![file](https://cloud.githubusercontent.com/assets/6359418/10867930/13bfcb98-80c0-11e5-8aa0-b71ba268df3a.png)
using zvol with 8k volblocksize
![zvol-8k](https://cloud.githubusercontent.com/assets/6359418/10867931/20cf583a-80c0-11e5-81be-20d48d43c2f7.png)
using zvol with 128k volblocksize
![zvol-128k](https://cloud.githubusercontent.com/assets/6359418/10867933/274acd98-80c0-11e5-8706-d639a92dba07.png)

**Comment by churchers** [comment]
I'm not sure about this one. It's getting to the stage where if the user is advanced enough to be wanting to alter the ZVOL block size, they can just alter the zvol property, which is probably just as easy as doing it through `vm-bhyve`.

I haven't tested, but I expect `bhyve` just uses the blocksize exposed by the device, so purely changing the ZVOL blocksize should be enough. Having said that I have now provided the ability to set additional disk options, which can be used to alter the blocksize reported by bhyve.

    disk0_opts="sectorsize=logical[/physical]"

One thing I might look at is altering the ZVOL blocksize to be a specific value instead of the default 8k at creation time, if there's a value that makes sense. I see `iohyve` now sets ZVOLs to 4k (which I think might be for other reasons), but according to your graphs it looks like 128k performs better.

**Comment by WanpengQian** [comment]
I think this volblocksize is readonly after creating. cannot be changed after that.
so that is why it should be done when creating zvol.
no metter what optimize value it should be, it would be better decided by user.

**Comment by churchers** [comment]
Ah ok, didn't realise the block size could not be changed.
Yes Ideally there needs to be some way to specify this before creating a guest then...

**Comment by churchers** [comment]
Might need a bit of tidying up, but I've added two new configuration options. These can be used to specify one or more properties to assign to ZFS datasets & ZVOLs as they are created. Multiple properties are separated by a space:

    zfs_dataset_opts="compress=off net.mydomain:custom=value"
    zfs_zvol_opts="volblocksize=128k"

These are passed into ZFS commands when creating any new dataset or ZVOL for the guest.

Obviously it makes most sense to specify these in a template, as in most cases you'll want the properties to be assigned to the dataset/ZVOL created when you run `vm create`.

**Comment by GogoFC** [comment]
Thanks. On my host raidz2 pool now I get up to 24MB disk writes with 128k, whereas 64k volblocksize capped it off at max 14MB. Comparing to before it's flying. I'll try 256 later.
![Screenshot (247)](https://user-images.githubusercontent.com/9360410/172366640-5bb1e6e5-f5e3-477a-beef-7f740120c5c0.png)
