### ISSUE TITLE
Unable to stop vm in Bootloader state

### ISSUE THREAD

**Issue by meabandit** [churchers/vm-bhyve#22]
```
# vm stop ns1
/usr/local/sbin/vm: ERROR: unable to locate process id for this virtual machine
root@bhyve1:/usr/local/bhyve # vm list
NAME            GUEST           CPU    MEMORY    AUTOSTART    STATE               
ns1             freebsd         2      512M      No           Bootloader (11691)  
ns2             freebsd         1      256M      No           Stopped             
ns_master       freebsd         1      512M      Yes [1]      Running (10604)     
owncloud_demo   freebsd         2      1024M     Yes [3]      Running (6013)      
pg              freebsd         4      4096M     Yes [2]      Running (2012)      
root@bhyve1:/usr/local/bhyve # ps aux |grep 11691
root  11691  100.0  0.0  553440   3884  3  R     1:13AM     0:41.21 bhyveload -c /dev/nmdm3A -m 512M -d /usr/local/bhyve/vm/ns1/ns1 ns1
```

**Comment by churchers** [comment]
Yes, normally `vm stop` is only used to stop the actual `bhyve` process once the guest is running. It sends a ACPI power button event to the guest which should cause it to shutdown and power itself off like a normal machine.

Normally of course, I would hope that the guest would not get stuck in the bootloader stage. This normally means the guest has been started with `vm start` before being installed, or something has gone wrong...

I have modified this function so that now, if it can't find a running `bhyve` process, it will look for a bootloader. If it finds a running bootloader it will ask if you want to force the machine off. Previously you would need to kill the `bhyveload` or `grub-bhyve` process manually.

**Comment by meabandit** [comment]
Works well, thanks.

**Comment by GogoFC** [comment]
I guess this is back with a vengeance :)
What I did was try to install Ubuntu, template was set at uefi="yes" it complained it was deprecated and it needs to be loader="uefi", too late now can't destroy it or start it, I don't see the two processes mentioned above.  Any advice how to destroy it?

```sh
root@FreeBSD:/home/gogoakira # vm list
NAME       DATASTORE  LOADER  CPU  MEMORY  VNC           AUTOSTART  STATE
symbolics  default    none    2    1024M   0.0.0.0:5900  No         Locked (FreeBSD)
root@FreeBSD:/home/gogoakira # vm console symbolics
/usr/local/sbin/vm: ERROR: symbolics doesn't appear to be a running virtual machine
root@FreeBSD:/home/gogoakira # vm destroy symbolics
/usr/local/sbin/vm: WARNING: symbolics appears to be running on FreeBSD (locked)
```
