### ISSUE TITLE
unable to locate switch id when adding interface to switch

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#223]
```
root@fbsd12:~ # vm version
vm-bhyve: Bhyve virtual machine management v1.2 (build 102059)

root@fbsd12:~ # vm switch info
------------------------
Virtual Switch: public
------------------------
  type: standard
  ident: vm-public
  vlan: -
  nat: -
  physical-ports: -
  bytes-in: 46848891 (44.678M)
  bytes-out: 100098542 (95.461M)

  virtual-port
    device: tap0
    vm: nvme

root@fbsd12:~ # vm switch add public em0
/usr/local/sbin/vm: ERROR: unable to locate switch id
```

**Comment by churchers** [comment]
Thanks for the report.

I really should get used to using `test` in the way it was fixed in pr #198. The way I use it causes the function to return an error code when the test succeeds. In this case I was checking if `ifconfig` returned an error code, which it didn't. However, because the test *didn't* succeed (`ifconfig` didn't return an error), the test itself returned an error.
