### ISSUE TITLE
vm-bhyve 'file not found' error for .config/switch

### ISSUE THREAD

**Issue by manasb** [churchers/vm-bhyve#23]
I experienced a problem when running 'vm init', the file '.config/switch' doesn't exist and vm-bhyve does not create it. I manually created the file with 'touch .config/switch' and 'vm init' completed succesfully.

thanks

**Comment by sdebnath** [comment]
@churchers based on the recent discussion on the freebsd-virtualization list, this error occurs when built from source as well. Could we just "initialize the switch" if it doesn't exist on vm init?

**Comment by churchers** [comment]
Hello,
Thanks for giving `vm-bhyve` a try.
Unfortunately this was a small bug in the version of `vm-bhyve` submitted to the FreeBSD ports tree, so this error will appear if you install from ports or with `pkg`. It can be safely ignored, the `vm init` command completes successfully regardless.

It was fixed in GitHub a few days after the port was committed. Rather than creating the switch file we just don't display an error if we can't find it.

I need to get the port updated although that's not always the easiest or quickest thing and so I've been waiting until I'm happy the code is stable.

**Comment by churchers** [comment]
*Intentionally leaving this issue open until port is updated so it's easily visible to any users who come here with the same problem*
