### ISSUE TITLE
Unable to remove virtual switch Related issue #167

### ISSUE THREAD

**Issue by rishabh27892** [churchers/vm-bhyve#238]
# vm switch list
NAME    TYPE      IFACE  ADDRESS  PRIVATE  MTU  VLAN  PORTS
public  standard  -      -        no       -    -     re0
# vm switch destroy public
/usr/local/sbin/vm: ERROR: failed to remove virtual switch
# vm switch info public
------------------------
Virtual Switch: public
------------------------
  type: standard
  ident: -
  vlan: -
  physical-ports: re0

#

**Comment by jasonbrowne** [comment]
We ran into this issue today.

**Comment by churchers** [comment]
Can you show the switch list and output when you try to remove it

**Comment by rishabh27892** [comment]
I just updated the ticket with more information...

**Comment by churchers** [comment]
Seems like vm-bhyve can't find the bridge interface looking at the list/info output.

Have you tried restarting the host? In 1.2 the method for finding bridge interfaces changed from using the description, which requires parsing `ifconfig` output, to groups, which can be queried directly.

**Comment by churchers** [comment]
Closing this issue. I believe it's due to upgrade from 1.1 -> 1.2 without letting vm-bhyve re-create switch interfaces. Please re-open if there's still an issue.

In 1.2 all switch interfaces should have a `viid-xxxx` group name assigned to them. If not, either restart the host or destroy the interface manually and run `vm init` to have vm-bhyve re-create it.

**Comment by GogoFC** [comment]
Back here in 2025. Just leaving this in case someone else runs into this. I create three switches with `-` named `proxmox-ceph` the ifconfig showed 

```
vm-proxmox-vm: flags=1008843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
	options=0
	ether 92:cb:4c:44:61:50
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
	groups: bridge vm-switch viid-fc593@
	nd6 options=9<PERFORMNUD,IFDISABLED>
```
and VM switch info showed

```
 ⚡ root@limhamn  /marabou/vm/.config  vm switch info proxmox-vm     
------------------------
Virtual Switch: proxmox-vm
------------------------
  type: standard
  ident: vm-proxmox-vm
  vlan: -
  physical-ports: -
  bytes-in: 0 (0.000B)
  bytes-out: 0 (0.000B)
```

`/marabou/vm/.config/system.conf` did not contain reference to those swtiches, they was not an entry to them at all. I rebooted and still got a message:
```
vm switch destroy proxmox-ceph 
/usr/local/sbin/vm: ERROR: unable to remove switch of unknown type
```
Then I realized when trying to destroy an non existent bridge like `vm destroy as;lfkjasfl` the error message is the same. 

I, then, added the swtich to `system.conf` manually and was able to destroy it. 

That was probably my bad trying to use a hyphen in the name since it adds another one.

I tested after reboot, creating switches with hyphens does not put them in the `system.conf` file.
