### ISSUE TITLE
Add support for manually configured bridges to vm switch

### ISSUE THREAD

**Issue by shonjir** [churchers/vm-bhyve#25]
In my configuration my VMs share the host LAN interface (igb0).  I have a vm switch configured (lan) which creates the bridge0 interface and binds to igb0:
```
switch_list="lan wan"
ports_lan="igb0"
ports_wan="igb3"
```
My rc.conf initially looked like this:
```
ifconfig_igb0="inet xx.xx.xx.5 netmask 255.255.255.0"
ifconfig_igb0_ipv6="inet6 xxxx::5 accept_rtadv"
```
After creating a test fbsd10 VM bound to 'lan', on boot that VM is unable to communicate with the host on IPv6 unless the host first sends a packet to the VM.

After some troubleshooting I was able to narrow this down to the bridge configuration.  Per the FreeBSD handbook, the bridge0 interface must be the addressed interface.  So, this is my 2nd configuration:
```
# new config moving IP to the bridge
cloned_interfaces="bridge0"
ifconfig_bridge0="addm igb0 up"
ifconfig_bridge0_alias0="inet xx.xx.xx.5 netmask 255.255.255.0"
ifconfig_bridge0_ipv6="inet6 xxxx::5 accept_rtadv"
ifconfig_igb0="up"
ifconfig_igb3="up"
```
The system comes up properly, but the vm script would not properly bind the tap interfaces to the bridges because they didn't have the vm script bridge identifiers.  So, I added the bridge identifiers and manually specified both bridges:
```
# new config moving IP to the bridge
cloned_interfaces="bridge0 bridge1"
ifconfig_bridge0="addm igb0 up description vm-lan"
ifconfig_bridge1="addm igb3 up description vm-wan"
ifconfig_bridge0_alias0="inet xx.xx.xx.5 netmask 255.255.255.0"
ifconfig_bridge0_ipv6="inet6 xxxx::5 accept_rtadv auto_linklocal"
ifconfig_igb0="up"
ifconfig_igb3="up"
```
The vm script now binds tap interfaces to the bridges properly, and vm's work as expected. (I added auto_linklocal as because link-local addresses are not automatically added to bridge interfaces even with _sysctl -w net.inet6.ip6.auto_linklocal=1_)

However, because the vm switch configuration automatically configures bridge interfaces there is potential for breakage if switch configuration is modified using 'vm switch' commands.

It would be ideal if in the switch configuration supported manually specified bridge interfaces as well as bridge autoconfiguration.  The bridge interface description could be configured by 'vm switch' to preserve existing behavior (in effect, vm would 'adopt' a manually configured bridge).  In such case 'vm switch destroy' should not be able to destroy a bridge that was manually configured.

The resulting switch configuration for this feature might look something like this:
```
switch_list="lan wan"
bridge_lan="bridge0"
bridge_wan="bridge1"
```

**Comment by churchers** [comment]
This is an pretty well though out idea.
I've always designed `vm-bhyve` to be fairly simple in that users shouldn't need to know how to create bridges or tap devices to start a guest - Just run start and have the networking sort itself out. The implementation of 'virtual switches' was one of the reasons I wrote `vm-bhyve`, in contrast to most other bhyve managers that require the user to handle most of the networking configuration.

I have however always known that some users may want configurations that `vm-bhyve` doesn't support, and having everything automated makes this difficult. (You're the first person I know of to come up against it)

This idea of allowing a custom bridge to be configured, and have `vm-bhyve` just assign its label to that is a great fix to some of these problems and I will look to implementing it.

The other half of the problem which I haven't really thought much about yet, mainly because no-ones hit it (as far as I know), is what to do if users what to to do something more clever with the `tap` interface that just add it to a bridge. The big complication there of course is that the tap interfaces don't exist until the guest is started, so users can't configure the networking until then. I may possibly look at additionally adding the ability for users to configure a fixed network device via configuration at some point, something like:

    network0_type="virtio-net"
    network0_switch="xyz" (or possibly even 'none')
    network0_device="tap10"

That way users can always configure a fixed device via `/etc/rc.conf` in any way they like, then just tell `vm-bhyve` to use that device. It wouldn't even necessarily need to be a tap interface.

**Comment by churchers** [comment]
Just to add, if you are currently using your configuration from above, I would empty out the `$vm_dir/.config/switch` file if you haven't already.

On reboot the host will run `vm init`, which will create bridge interfaces for any switches listed in the configuration, which in you case will end up with 2 bridges for each switch, as you're creating them manually in `/etc/rc.conf`.

With the switch configuration file empty, `vm-bhyve` will not attempt to create any bridges automatically, but it should still happily find your manual bridges when starting guests.

**Comment by shonjir** [comment]
In all honesty it's just a summary of troubleshooting weird connectivity issues with guests.  Things had been working find with one guest as virtual firewall, especially after I moved DHCP from the guest to the host.  When I added a 2nd guest as a straight VM and it wouldn't acquire an address that took some noodling.

Interesting point about the tap interface - it seems reasonable to extend the bridge idea to cover interfaces that have already been provisioned.  It would allow the user to do other types of advanced configuration outside the confines of autoconfiguration, yet would retain the current plug and play behavior.  

Good tip re: $vm_dir/.config/switch - I'll do that.  Wasn't sure what would happen.

**Comment by churchers** [comment]
I've added support for this and a new command to 'import' existing bridge interfaces. Assuming you have cleared out any existing virtual switches, you should be able to run the following:

    vm switch import lan bridge0
    vm switch import wan bridge1

This will add the bridges to vm-bhyve configuration, and will assign the relevant description so we can find them when starting guests. It also causes the description to be added on boot, so users don't need to manually assign the vm-bhyve label to the bridge.

These show up in `vm switch list` as "manual" switches. The idea being that this is for instances when you want to manage your own bridge. As such, we error out if you try and run one of the `add`, `remove`, `vlan` or `nat` functions on it.

If the `destroy` command is used, it remove the interface description and vm-bhyve configuration, but leaves the bridge intact.

**Comment by churchers** [comment]
Also, having spent an hour or so trawling through `lib/vm-switch`, I was actually wrong about what would happen on reboot. Since originally writing `vm-bhyve` I've improved the switch init to only create bridges if they don't already exist. This was mainly so if users run `vm init` more than once, then don't end up with loads of bridge interfaces.

As such, the rc.conf bridges would probably already exist before `vm-bhyve` starts on boot, and it wouldn't of created duplicates.

**Comment by churchers** [comment]
I've now added the ability to use an existing tap device (or anything else bhyve might support) instead of having it created at run-time. I've also removed the requirement for `networkX_switch` to be present, as the user may have already bridged the interface, or even done something more clever with it.

    network0_type="virtio-net"
    network0_device="tap2"

The switch option is still supported either way so it's fine if you want a manual tap device, but still want vm-bhyve to bridge it automatically.

**Comment by nbari** [comment]
Hi @shonjir I am having exactly this same behavior,  https://serverfault.com/q/878590/94862

How are you configuring `/etc/rtadvd.conf `  are you using your main interface or `bridge0` ?

**Comment by shonjir** [comment]
@nbari - in all honesty I'm not using rtadvd on the host at this point - the host is just another device on the bridged network in my current config, and my IPv6 network is configured by my firewall guest.

The bridge interface is my addressed interface, with all member interfaces unaddressed.  This has been the most stable configuration for me.  I would recommend you do the same and configure rtadvd using the bridge interface.

I never could get IPv6 automatic addressing working properly with the host as a router.  At the time I was using both public and site-ULA addressing, which likely had a lot to do with it - the host advertised the ULA addresses, the firewall advertised public, and the guests were pretty much confused as to which routers were "authoritative".  I ended up abandoning the whole arrangement in favor of the simpler (albeit less functional) setup I'm running now.

**Comment by nbari** [comment]
Hi @shonjir thanks for the reply, the problem I am facing when enabling also `auto_linklocal` is that the ipv6 is removed, I am getting this messages:

    bridge0: IPv6 addresses on igb0 have been removed before adding it as a member to prevent IPv6 address scope violation.

But seems that by using `net.link.bridge.allow_llz_overlap=1` could help, will continue giving a try.
