### ISSUE TITLE
vm should not overwrite /usr/local/etc/dnsmasq.conf

### ISSUE THREAD

**Issue by shonjir** [churchers/vm-bhyve#26]
Currently, vm's NAT feature assumes that vm is the only user of dnsmasq on the host.  This is not necessarily true - I currently use dnsmasq to provide local DNS and DHCP services.  The current behavior of vm would overwrite my dnsmasq configuration if I were to inadvertently enable NAT functionality.

Rather than assuming that the current dnsmasq.conf may be overwritten vm should instead write a sample vm-specific dnsmasq configuration file that might be included by the administrator.

**Comment by churchers** [comment]
Yes I do mention in the man page that `vm-bhyve` takes over the dnsmasq configuration. I've not really done much development on the NAT support other than get it to the point where it works. It was my first time doing anything with dnsmasq and was implemented pretty quickly. It's more of a 'it's nowhere near perfect but works it you want to use it' kind on thing.

The problem I had was making sure it worked without any side effects, the most obvious being that dnsmasq likes to listen on all interfaces by default, as well as making a few other changes to make sure no host information can be leaked into the guests. I also thought that while I could just add the interface specific DHCP entries to the existing file, the rest of the configuration could be such that it wouldn't work as expected, which is why I went with the simple option of a full configuration I know works.

dnsmasq actually isn't really required to make the NAT functional. It's just a nice feature to have DHCP work so guests can be booted and just get network connectivity automagically. Maybe I need to stop trying to make everything work by magic, and just give users a sample configuration file as you suggest; On configuring NAT just output something along the lines of "NAT functionality is enabled but guests will require a private IP address assigning manually. To enable DHCP functionality, the following dnsmasq configuration can be used" - Then output a sample dnsmasq configuration that the user can either use fully or adopt into their existing configuration.

The only issue is that it's possible that the bridge specified in the configuration could change, as switches are auto generated on each boot. However 99% of the time it would be pretty consistent as we always create the bridges in the same order.

**Comment by shonjir** [comment]
I don't have any suggestions as to how this could be automated as there are so many different ways to configure dnsmasq.  I don't use NAT either - I actually noticed the behavior while looking through the code while troubleshooting the shutdown issue.  

I've implemented my own workaround by specifying a non-default dnsmasq_conf config in rc.conf, but given how complicated my dnsmasq.conf is for my deployment I would have been more than a little irritated if I'd first encountered the feature by enabling NAT.

**Comment by churchers** [comment]
I've updated the GitHub master for this.
We no longer have any requirement for `dnsmasq` to be installed for NAT functionality - all the NAT comes from `pf`.

We generate a sample dnsmasq configuration in `/usr/local/etc/dnsmasq.conf.bhyve`. If the user wants DHCP they can use this config directly or merge with any existing configuration they have. Or they can use any other DHCP method they might want to use.
