### ISSUE TITLE
vm-bhyve swap space usage

### ISSUE THREAD

**Issue by paulesson** [churchers/vm-bhyve#268]
Just started using vm-bhyve, vm-bhyve-1.2.3, on FreeBSD 11.2-RELEASE-p4 and noticed three processes, one for each VM, using swap as indicated by top -w.  The processes are running the "vm" script as follows /bin/sh /usr/local/sbin/vm -tf _run  {vm name}.  Is this expected behaviour?

**Comment by churchers** [comment]
Hi Paul,

Yes this is expected. `vm-bhyve` runs in the background while the guest is running. This process will catch the exit code of bhyve and restart the machine on guest reboot, or remove tap devices / clean up on shutdown.

I don't know enough about kernel/memory to know why it is using swap space. I would guess that because the script does nothing which bhyve is running other than wait, the system may move it to swap  as the memory is not being touched for extended periods of time.

**Comment by paulesson** [comment]
Understood. Thanks for the explanation
