### ISSUE TITLE
How to add custom filesystem (virtio-9p/VirtFS) to the virtual config?

### ISSUE THREAD

**Issue by petr-fischer** [churchers/vm-bhyve#306]
Hello! I want to add virtio-9p config to vm-byve, like in this post:
https://lists.freebsd.org/pipermail/freebsd-hackers/2016-February/049068.html

Is it possible? Thanks!

**Comment by dch** [comment]
not yet unless you build custom kernel + custom iso for installing into the vm. See https://reviews.freebsd.org/D10335 for some patches to help achieve this.

**Comment by Duffyx** [comment]
I think we might start looking at this one since it has landed in current recently.
ATM I have tried:
bhyve_options="-s 15,virtio-9p,sharename=/storage/movies"
But I have not had any success starting the virtual machine with this option. I do not see any other logical place where to put the extra param.

**Comment by Duffyx** [comment]
NVM, I'm an idiot 🥇!
I forgot to recompile my world and kernel after the patch landed.
When I now specify as I stated above it works fine.

**Comment by JoeKun** [comment]
@driesmp's technique with `bhyve_options` worked great for me on FreeBSD 13.1 (and no need to recompile the kernel nowadays). Thanks!

By the way, I agree that adding a convenience command to `vm-bhyve` for setting up such shared directories would be amazing. That seems to me like one of the very first things most people will want to do after successfully setting up a virtual machine with bhyve.
