### ISSUE TITLE
centos template not valid for Centos 6

### ISSUE THREAD

**Issue by meabandit** [churchers/vm-bhyve#32]
centos os type tries to boot centos 6 with something like:

linux /vmlinuz-2.6.32-573.el6.x86_64 root=/dev/mapper/centos-root

However in standard linux fashion CentOS has decided to arbitrarily rename foundational elements for no particular reason.

For CentOS 6 default, something like 
```
root=/dev/mapper/VolGroup-lv_root
```
is needed instead.

I don't know how you wish to handle this as custom grub is already supported, but it was a bit of a surprise when CentOS 6 didn't work.

**Comment by churchers** [comment]
I'm sure when I was testing CentOS 6 it defaulted to using standard partitions on the disk rather than LVM. But yes, Linux is becoming a real pain as the boot commands change depending on just about everything, even between minor versions sometimes.

Linux support is the only thing I'm not particularly happy with but I'm not sure what the best answer is. There's another issue on here that contains some good information.

Rather than create dozens of different guest types, I may look at some way of providing boot commands through the template, so I can just start building up templates for different scenarios. That would probably end with eventually just having a `linux` guest, and always using a `boot_commands` file rather than trying to do it all internally.

**Comment by meabandit** [comment]
A standard partition would have resulted in something like this in boot.cmd: 
```
root=/dev/vda1
```
/dev/mapper/centos-root(from the auto-generated boot.cmd) indicates LVM since it is a subset of Device Mapper and is the new default for 7( <- pretty sure on this, not certain).

If it was me, I'd just rename centos to centos7 and let us centos 6 users muddle through even though there are many more centos 6 installs now.

But yes, hopefully grub-bhyve can grow some kind of -auto feature which automatically loads most current kernel etc otherwise maintaining linux guests is going to be painful.

**Comment by churchers** [comment]
Hopefully you should be able to get this working now.

I've finally given up on trying to hard-code the grub commands and have moved them into the configuration file (In hindsight it was a terrible idea). Now, as long as there are grub commands that will get the guest to boot, you should be able to get it working with `vm-bhyve`.

Have a look at the README and sample templates, but the basics are as follows

- By default, `grub-bhyve` is run on the guest console, so you can use `vm console guest` to access it, and enter any boot commands needed manually.
- If you know the commands needed, they can be added to the guest configuration file using the `grub_runX` and `grub_installX` options, and these commands will then be automatically passed into `grub-bhyve`.
