### ISSUE TITLE
Feature Request: custom tap ip address

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#39]
need a new options to set the tap address so guest can communicate with hosts.
when a vm start, a new tap device will add automatically.
(when tap device is not specified by config) 

currently, there is no way to set the ip address of that tap device.
it would be nice to have such feature. 
such as by adding the following to vm config
```
network0_tap_ifconfig="inet 10.0.0.1 netmask 255.255.255.0"
```
vm-bhyve will set the newly created tap device properly.

**Comment by WanpengQian** [comment]
I have been thinking this for a while. maybe it is not a good idea to assign ip address to every tap device. instead. we create a new tap device(not belonging to any vm) for switch. and set the ip address for this tap device. then vm and host can communicate flawlessly.

and this is the be job of ```vm switch```

**Comment by WanpengQian** [comment]
After a little digging. I found it is better to set the ip address in bridge interface rather to create a new tap device and assign ip address to it. 
and for each tap device of each vm, the ```network0_tap_ifconfig``` is useful when not adding the tap device to bridge interface

**Comment by churchers** [comment]
Yes I was going to reply to the original message saying I don't think assigning an IP to the tap in the host was a good idea.

I think the ability to assign an IP to the bridge is the best option, although I'll have to put some thought in the best way to implement this. I think I'd prefer to limit this to assigning an IP to a bridge than complicate matters by allowing users to assign an IP to a tap as well. If users want guests to communicate with the host, they can create a 'local' switch (bridge) with an IP configured, and add a guest interface to it.

**Comment by WanpengQian** [comment]
This are two separate problems.
1. assign IP to bridge. this is the job relate to vm switch. no relation to any vm client.
2. assign IP to tap device. this is related to specify client.
If a client only want to communicate with vm host, this is the best way. while creating a extra bridge and add tap to bridge/assign IP to bridge make it more complex.

**Comment by shonjir** [comment]
I know this is an older issue but having experimented recently with a VM as Internet gateway and the host as a router I thought I'd add my 2c to the conversation.

I think I'm in agreement with @WanpengQian that there is a need to be able to use a specifically provisioned tap interface for a single guest specifically for host-only configurations.  I used the local bridge configuration as a workaround, but for host-only communication it's a bit of a kludge.  Setting an explicit tap interface on the VM would've been substantially cleaner.

I've experimented with configurations where I've provisioned a 'tap99' interface via rc.conf and configured this explicitly in the guest.  It worked, but because vm-bhyve doesn't respect this configuration it will deprovision the tap when the guest shuts down because it assumes all taps are auto-generated.  If the statically created tap interface name happens to collide with autogenerated tap name it will be reconfigured.

I don't agree that ip addressing should be assigned within vm-bhyve; such functionality is already present in rc.conf and would add unnecessary complication to the config.

A feature that allows a specific tap interface to be marked as 'manual' would be sufficient.  Interfaces marked as manual would need to be excluded from the tap provisioning and deprovisioning steps.

Tap interfaces with ip addresses should not be bridge members.  My experience has been that bridge members with ip addresses do not communicate reliably.  The handbook recommends setting the address on the bridge in such cases:

> If the bridge host needs an IP address, set it on the bridge interface, not on the member interfaces.

In addition, when these interfaces need to be firewalled the handbook recommends firewalling the tap interfaces rather than the bridge when directionality is important.  It's not possible to do that without statically defining the tap interface, so I think there are multiple use cases that could be addressed by this feature.

**Comment by churchers** [comment]
It should already be possible to use a manual tap device by using the `networkX_device="tapX" configuration option. Let me know if this isn't working for you.

This combined with the "manual" switch feature should allow pretty much any custom configuration to be used.

**Comment by WanpengQian** [comment]
@shonjir 
I don't think assign the IP address to special TAP device is the business of host. since TAP device can be dynamic create by vm-bhyve or fix name by tc.conf.

- dynamic

 creation of TAP device. since host cannot know which TAP belong to(or connect to) which guest, it is obviously the matter of guest to set the TAP interface's address.

- fixed creation of TAP device. in this case, TAP device is created by rc.conf, so it is the business of rc.conf to set the IP address.

**Comment by churchers** [comment]
I don't see why a guest's IP address should ever be set in the host `rc.conf`, regardless of whether the interface is manual or automatic. The tap device belongs to the guest and should be configured inside the guest, as with any other hypervisor.

If you are using firewall rules that are dynamic based on the IP addresses in use, and so need to know the guest's addresses, then I would suggest it's the rules that need to be reconsidered.

I could possibly add the ability to give an automatic switch an IP address, which would be configured on the bridge. However the same result can be achieved by importing a custom bridge.

On my test system I actually have `re0` as my primary interface which is on my LAN. My guests are bridged to this so they can get DHCP & Internet access, and while possibly not recommended, I've not noticed any issue communicating between host/guests.

**Comment by churchers** [comment]
Closing this for now as more unusual configurations can be achieved using custom bridges and tap devices. Please reopen if anything isn't working properly.
