### ISSUE TITLE
Template for Windows?

### ISSUE THREAD

**Issue by Gwynei** [churchers/vm-bhyve#4]
Hi!

I am planning of building a server with FreeBSD, ZFS and bhyve.

Aside of a debian VM, I want to create a Windows (Server 2012 R2) VM as well, according to the latest news this is now officially supported in bhyve!

Do you have any plans of creating a Windows template?

**Comment by churchers** [comment]
Hello, thanks for your interest.

I've looked at the information on the mailing lists and Windows support shouldn't be too much of an issue. The `bhyveload` stage is no longer required so it's just a case of running the `bhyve` command with the right arguments.

At the moment Windows is only supported in FreeBSD-CURRENT, which means downloading and building FreeBSD from source. There is also no VGA support, so Windows can only be installed by creating an unattended installation script, building that into a custom ISO, then setting the installer off basically blind (apart from a simple text service console on COM1).

Because it requires CURRENT, and manual ISO creation, it's still not particularly user friendly so I'm not putting too much priority on it. At the moment the biggest issue for me is finding capable hardware spare that I can build CURRENT on, but I do hope to have at least one Windows version tried in the next couple of weeks.

**Comment by churchers** [comment]
Ok well I found a standby server that used ZFS boot environments, so it was fairly easy for me to create a separate environment to run CURRENT. I can easily switch back to exactly as it was when I've finished. (Good old ZFS & beadm :)

I have tested Server 2012R2 and it seems to run fine. There is now a `windows.conf` sample template you can use as a basis. The important thing is to have guest=windows, uefi=yes, and the disks must all be ahci-hd. Windows has no support for the virtio-blk devices.

As I want `vm-bhyve` to function the same for all guests, and not require any dev tools, you need to provide the re-packed Windows ISO file yourself. I've put some instructions at the bottom of the README.md file. Once you have the ISO, and have downloaded the UEFI firmware, it should work just like any other supported guest.
