### ISSUE TITLE
NetBSD 9.2 doesn't work with template

### ISSUE THREAD

**Issue by jepace** [churchers/vm-bhyve#427]
After installing NetBSD 9.2, the guest reboots but stops at:

[   1.5731285] boot device: ld0
[   1.5731285] root on ld0a dumps on ld0b
[   1.5731285] vfs_mountroot: can't open root device
[   1.5731285] cannot mount root, error = 16
[   1.5731285] root device (default ld0a):

If you type dk0 there, it will boot fine, but this will happen each boot.

The problem comes from the template config line:
grub_run0="knetbsd -h -r ld0a /netbsd"

Changing "ld0a" to "dk0" fixes it for me.

(To fix your already installed guest, make similar changes in the guest's grub.cfg and <guestname>.conf.  Not sure if both are necessary but it works.)

**Comment by jeroenlaylo** [comment]
The templates do need some updating. Not familiar with NetBSD myself, how representative is the `dk0` identifier nowadays? I am in the process of making a pull request with template updates.

**Comment by churchers** [comment]
I've updated this template. I'm not a NetBSD user so let me know if there's any further updates that should be made to this.

**Comment by spchamp** [comment]
With NetBSD 9 I was able to boot the installation by running vm-bhyve under 'install', then dropping into the bootloader on the installer image, then providing the commands to the bootloader in order to boot the installed system. This was with the NetBSD VM configured to use EFI. I was accessing the bhyve guest over VNC, with Remmina.

The walkthrough for the workaround I'd used, approximately: With the NetBSD boot.iso from the initial installation for NetBSD under bhyve, to boot after the installation: run `sudo vm install -f boot.iso`. This should present a boot console from the installer image, on the terminal. This can be run under an existing termux session.

At the bootloader prompt on the terminal, select option 3, "Drop to boot prompt"

In the NetBSD bootloader, `help` will list available commands. The `dev` command would be used to determine what device names are available for boot, depending on how the system was installed (e.g with or without volume labels onto some disk partition layout). 

In the installation I was using, I'd created a gpt disk under the uefi guest for NetBSD. This is what the `dev` command shows me, in the NetBSD bootloader for this sytem:

~~~~
> dev
disk hd0 mediaId 0 size 16 GB
  NAME=NBESP(EFI System) NAME=NBROOT(NetBSD FFS) NAME=NBSW(NetBSD Swap)
disk hd1 mediaId 0 size 64 GB
  hd1a(4.4LFS)
disk cd0 mediaId 1
  cd0a
net net0 58:9c:fc:0e:52:b3 pci0,6,0
default cd0a
~~~~

I can boot the installed system from here, with the following command to the NetBSD bootloader.

~~~~
> boot NAME=NBROOT:netbsd
18476928+668736+1428416 [869892+1252920+894518]=0x16e1420
Loading NAME=NBROOT:/stand/amd64/9.2/modules/cd9660/cd9660.kmod 
~~~~

From there, it runs.

I think NetBSD's bootloader is crashing on the zero-length null.iso file. 

Would it be possible to add an option to the vm-bhyve config to disable the mounting of the null.iso under EFI installations? Since the installer does not mount the null.iso, I think that's why this workaround works.

I hope this helps, any. I'm not all sure of how to address this in a patch
