### ISSUE TITLE
Multiple Compute Nodes

### ISSUE THREAD

**Issue by biancalana** [churchers/vm-bhyve#432]
Hi Guys,

 There's any recommendation of how to configure and use multiple compute nodes + shared storage ? 

 I'm build a home lab with two compute nodes with a NFS shared storage and my main doubt is that all the config reside in the vm_dir/.config/system.conf, there isn´t any separated config per compute node. If the configs can´t be splited per compute node I need to have two identical machines (network interfaces, etc).

**Comment by churchers** [comment]
Hello,

Good point. It may be worth me looking into storing the configuration somewhere other than the vm directory. Of course, for multiple nodes to work seamlessly, ideally you want all nodes to have exactly the same virtual switches available (although the actual interfaces used on each host may be different).

Two most obvious solutions for me -

1. Install vm-bhyve using a local vm_dir, then add the nfs location as a second datastore. That way the configuration can be managed independently on each host.
2. Configure the networking manually using `rc.conf`, then just add them to vm-bhyve as manual switches (I usually do this to be honest as I generally prefer to manage all the networking myself through `rc.conf` rather than having it dynamically created by vm-bhyve)
