### ISSUE TITLE
vm migrate options

### ISSUE THREAD

**Issue by cirrusflyer** [churchers/vm-bhyve#475]
I've successfully used this here as long as you're using vm-bhyve v1.5.0:

https://github.com/churchers/vm-bhyve/commit/0d5905bd69222602d2017df4afcec6e0dfd68200

I did notice the "-s" flag produces an error.  And is there any way to display migration progress?  Also, is "socat" still required?

**Comment by anteract** [comment]
I can answer these, since I use this a lot.

 

First the "-s" is gone, isn't needed anyway.

 

socat is used, so yes, install it.

 

And to show a progress bar, install "pv" (pkg install pv), find the "zfs send" lines (2 of them) in the library, and do this:

 

line 230:   zfs send -Ri "${_inc}" "${VM_DS_ZFS_DATASET}/${_name}@${_snap}" | ssh ${_host} zfs recv "${_rdataset}/${_rname}

turns into:   zfs send -Ri "${_inc}" "${VM_DS_ZFS_DATASET}/${_name}@${_snap}" | pv | ssh ${_host} zfs recv "${_rdataset}/${_rname}

 

Line 233:   zfs send -R "${VM_DS_ZFS_DATASET}/${_name}@${_snap}" | ssh ${_host} zfs recv "${_rdataset}/${_rname}"

turns into:   zfs send -R "${VM_DS_ZFS_DATASET}/${_name}@${_snap}" | pv | ssh ${_host} zfs recv "${_rdataset}/${_rname}"

 

ymmv

 

From: cirrusflyer ***@***.*** 
Sent: Friday, August 19, 2022 9:12 PM
To: churchers/vm-bhyve
Cc: Subscribed
Subject: [churchers/vm-bhyve] vm migrate options (Issue #475)

 

I've successfully used this here as long as you're using vm-bhyve v1.5.0:

 <https://github.com/churchers/vm-bhyve/commit/0d5905bd69222602d2017df4afcec6e0dfd68200> 0d5905b

I did notice the "-s" flag produces an error. And is there any way to display migration progress? Also, is "socat" still required?

**Comment by anteract** [comment]
Crap, sorry, spoke without checking, it appears the migrate code no longer includes the socat commands.  They were replaced by the zfs send stuff above.  Ignore that part of my post.
