### ISSUE TITLE
Specify a custom -l bootrom command for a .fd file?

### ISSUE THREAD

**Issue by 0w8States** [churchers/vm-bhyve#519]
I'm just getting started with vm-bhyve, but I ran into an issue where I need to specify my .fd file. How would you do this inside the .conf file for the vm?

I usually use "-l bootrom,/usr/local/share/uefi-firmware/BHYVE_BHF_UEFI.fd" when launching my vm from bhyve. I noticed these two parameters are listed in the man page, but not quite sure how to use them to specify the .fd file.

bhyveload_loader=""
bhyveload_args="-e machdep.hyperthreading_allowed=0"

**Comment by GogoFC** [comment]
Lucky for you I found out about this today. Assuming that you're trying to boot UEFI with EFI variables.
As I have no idea what that hyperthreading bhyveload argument would do to a guest at all.

To use uefi bootloader set `loader="uefi"` and  `graphics="yes"`
To use UEFI variables add  `uefi_vars="yes"` to the config file.

```sh
loader="uefi"
graphics="yes"
uefi_vars="yes"
xhci_mouse="yes"
```

Found out about it here:

https://github.com/churchers/vm-bhyve/issues/449

https://github.com/churchers/vm-bhyve/blob/ec0e12e97465822d65ab32e791049d69791d49cb/lib/vm-run#L306

The complete config file I use for Debian 12 is:

```sh
loader="uefi"
cpu=4
memory=4096M
network0_type="virtio-net"
network0_switch="public"
graphics="yes"
xhci_mouse="yes"
graphics_res="1600x900"
#zfs_zvol_opts="volblocksize=128k"
disk0_name="disk0"
disk0_dev="sparse-zvol"
disk0_type="virtio-blk"
uefi_vars="yes"
```

Ubuntu works without uefi_vars because it stores the bootx64.efi in a standard location

**Comment by 0w8States** [comment]
Thanks for the assist @GogoFC

It led me in the right direction. I noticed in the vm-run a few lines up that there is a loader type of "uefi-custom". I just did a copy of my custom .fd file to the base VM directory and used the flag loader="uefi-custom". It solved all my issues!
