### ISSUE TITLE
"msdos1" is hard coded as boot-device

### ISSUE THREAD

**Issue by kmhamich** [churchers/vm-bhyve#52]
Any Linux Virtual-Host will be started by the following command where the partition "msdos1" is hard coded.

```
grub-bhyve -r hd0,msdos1 -m "${vm_dir}/${_name}/device.map" -M "${_memory}" "${_name}
```

this should not be hard coded to msdos1, you cant expect msdos1 to be the boot-partition. There should be a config option for this.

**Comment by churchers** [comment]
`grub-bhyve` support has been completely rewritten.
Have a look at the GitHub readme and sample templates.

The following are all functional configurations that I have tested

Ubuntu with grub automatically picking up the `grub.conf` file and booting without any other intervention:
```
grub_run_partition="msdos1"
```

NetBSD:
```
grub_run0="knetbsd -h -r ld0a (hd0,msdos1)/netbsd"
grub_run1="boot"
```

NetBSD, with partition specified directly to `grub-bhyve` rather than in the grub commands:
````
grub_run_partition="msdos1"
grub_run0="knetbsd -h -r ld0a /netbsd"
grub_run1="boot"
```

**Comment by kmhamich** [comment]
I will have a look at it. Thx for your efforts!
