### ISSUE TITLE
ability to set ip/subnet of vm interfaces 

### ISSUE THREAD

**Issue by nathanaherne** [churchers/vm-bhyve#70]
I run pf on my host, which will block incoming/outgoing traffic from a VM unless configured to allow traffic to the IP. To allow the VM to work, I need to configure pf before creating the vm and then manually set the vm's IP. 
I am running the switch in bridge mode connected to the external interface.

**Comment by churchers** [comment]
I'm not sure what the best answer is here. Normally the IP should be set inside the virtual machine, not on the host, and so the address won't be known to `pf`.

Is it possible to modify the firewall rules (possibly containing a table of your guest addresses), rather than relying on `pf` automatically picking up addresses from the interfaces.
