### ISSUE TITLE
Ubuntu guest failing to reboot

### ISSUE THREAD

**Issue by manasb** [churchers/vm-bhyve#75]
I am seeing this error in /VM/$guest/vm-bhyve.log

`loader returned error 1`

What does it mean and how can I fix it?

This happens when a Linux guest tries to reboot.

I am running `vm: Bhyve virtual machine management v0.9.19`

**Comment by manasb** [comment]
@churchers Could something like an expect script handle the grub-bhyve commands?

**Comment by churchers** [comment]
I'm really struggling to find a good solution for Linux guests at the moment. No one seems to have anything that works better than what I'm already doing. It's a shame `grub-bhyve` doesn't have some build in method of supplying boot commands.

I tried writing the commands directly into the `/dev/nmdm` device, which worked perfectly while I had cu running on a second session (so I could watch the commands going in). Unfortunately after several hours of converting all the code to use this method, when I came to test without having the console open, it wouldn't work... 

I also looked at your suggestion of `expect`, as I can't find anything in base I can use to send commands to the nmdm device. After a lot of hassle (OpenBSD would boot intermittently, but would run perfectly if I tried to turn expect logging on - really was a frustrating day...), that also seemed to work. Unfortunately if you open the console for a guest and reboot it, it won't reboot because you have the nmdm device open, and expect can't write to it. Being able to reboot a guest from the console and watch it boot back up was a nice feature I don't really want to lose.

I am hoping that as `bhyve` gets better, I'll be able to use UEFI & UEFI graphics so that Linux will just boot like a real machine, and the bootloader/console will be accessible via vnc. It would be a slight shame though as grub-bhyve skips most of the usual boot crap so is very fast, and it's nice having proper serial access to the console.

At the moment I'm just planning on moving all the grub commands into the configuration file. If no commands are specified, I will just run grub-bhyve on the guests console. This way you can access grub with `vm console guest`. Once you know the right commands to boot successfully, these can be entered into the guest configuration file. It's now fairly clear trying to hard code these commands into `vm-bhyve` was a bad idea.

Just out of interest what Linux distribution are you using?

**Comment by churchers** [comment]
Closing this for now, reopen if there are still problems with recent versions.
Grub handling has been completely rewritten in 0.10 & 0.11.

I've had no issues with Ubuntu 14 & 15, both of which boot using the guest's grub.cfg file as long as grub-bhyve is told what partition to look in

    grub_run_partition="msdos1"

**Comment by manasb** [comment]
I'm testing this out now with an old VM that I was running with plain ```bhyve``` commands. I am migrating it over to vm-bhyve and trying to figure out if I can get it to boot automatically. It's nice to use grub.cfg because no configuration would need to be changed on the host in between kernel updates of the Linux guest.

**Comment by churchers** [comment]
Let me know how you get on with this. I've done quite a bit of testing with the new grub support recently and it seems fairly stable to me. If you were running the guest fine using grub-bhyve/bhyve manually, I can't see why it shouldn't be possible to run it with vm-bhyve.

I've put a page on the wiki that explains that various ways grub can be configured, although I'm not sure how clear it is.

If you have grub2 installed in the guest, you should be able to get vm-bhyve to pick up the guest's own configuration file using the following set of configuration options:

    grub_run_partition="A" # boot partition, defaults to 1
    grub_run_dir="B" # directory to look in for grub.cfg, defaults to /boot/grub
    grub_run_file="C" # name of grub file to look for, defaults to grub.cfg

If you've been manually entering commands into the `grub>` prompt, these can be provided using the `grub_run` config options:

    grub_run0="linux ..."
    grub_run1="initrd ..."

**Comment by churchers** [comment]
If you're using a recent copy from GitHub, there's also a foreground option which is really useful when you're testing and would rather just have the guest start directly on your screen instead of hidden away on the nmdm console.

    vm -f start guest

**Comment by manasb** [comment]
@churchers I've got an Ubuntu 14.04 guest working with the suggested settings. Thank you.
