### ISSUE TITLE
Auto enable graphics_wait when using install command

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#91]
graphics_wait is useful when installing OS
(when HDD has contents, windows installer will not auto start, while display an 
press any key to boot from cdrom...)

It is sweet automatic adding wait parameter when using install command.
and this will avoid adding graphics_wait="yes" when install OS, and remove it after OS installation.

**Comment by churchers** [comment]
Good idea.

I've updated the code to set `graphics_wait="auto"` by default. In this mode the `wait` option is added in we are running in install mode. Values of `yes` and `no` can still be used to enable or disable the wait option permanently.

The only downside to this is that we only generate the bhyve devices once when `vm-bhyve` first starts. Because of this, if you reboot after install, the guest will wait for the vnc console again. You need to shutdown and restart the guest with `vm start` to perform a normal boot. Don't think this is a massive issue, the same thing will happen if you use `wait=yes`. If needs be I can move the code that generates the `fbuf` device inside the main bhyve loop.

**Comment by WanpengQian** [comment]
I saw when I install windows using ```vm install``` command, vm-bhyve first using installaion iso from command line, and then switch to null.iso after first reboot.

so for ```wait=yes```, I think it is better to let ```wait=yes``` gone after first reboot.
for windows, Installer will reboot several times. actually, only first time, as power on, needs our attention.

**Comment by churchers** [comment]
Ah you're right, Windows reboots twice during install and we don't really want to wait as it removes the ability to just leave it and let it install. Was trying to avoid it but I'll move the fbuf device out from `_devices` and into a separate variable. I can then reset this variable for each run.

**Comment by churchers** [comment]
Bit ugly but finally got around to fixing this so that the `wait` option is only given the first time when in auto mode.
