### ISSUE TITLE
mv: rename /vpool/vm/vm123/vm168.conf to /vpool/vm/vm123/vm123.conf: No such file or directory

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#95]
trying clone.
```
root@fbsd11:~ # vm clone vm168@20151115 vm123
mv: rename /vpool/vm/vm123/vm168.conf to /vpool/vm/vm123/vm123.conf: No such file or directory
tail: /vpool/vm/vm123/vm123.conf: No such file or directory

```
a bug in code.
```
    # update new guest files
    mv "${VM_DS_PATH}/${_name}/${_old}.conf" "${VM_DS_PATH}/${_name}/${_name}.conf"
    unlink "${VM_DS_PATH}/${_name}/vm-bhyve.log" >/dev/null 2>&1
```
should be ```"${VM_DS_PATH}/${_old}/${_old}.conf"```

**Comment by churchers** [comment]
The code should be correct. Once the guest has been cloned to `VM_DS_PATH/name`, it will still contain a config file for the old guest. Inside this new folder, the file is then renamed from `old.conf` to `name.conf`.

Is this the same as issue #36 with a guest that has been renamed since creating the snapshot?

That's a difficult issue to fix as I want to try and avoid any breakage for existing users, for a bug that is a bit of an edge case. For now I have added a check to error out if the rename fails, and added a message to say the configuration will need fixing manually.

**Comment by WanpengQian** [comment]
Sorry. I using the snapshot that has the #36 issue.
currently works fine.
