### ISSUE TITLE
pf_enable check is incomplete

### ISSUE THREAD

**Issue by basiliocat** [churchers/vm-bhyve#98]
pf_enable="YES" can be set either in /etc/rc.conf or in /etc/rc.conf.d/pf, but check is performed only for /etc/rc.conf (and also for /etc/rc.conf.d/vm)

**Comment by churchers** [comment]
I use `load_rc_config` from `/etc/rc.subr` to load all the `vm` rc variables. From what I can see this should be sufficient to check all supported locations. It definitely works on my test system if I move the setting into `/etc/rc.conf.d/vm`.

I have added a call to `load_rc_config "pf"` before checking `pf_enable` so that all locations are checked for this setting.
